const demoArticles = [
    {
      id: 1,
      title: "Breakthrough in Quantum Computing",
      content: "Researchers have achieved a major milestone in quantum computing, paving the way for more secure encryption and faster processing.",
      image: "https://via.placeholder.com/400x200.png?text=Quantum+Computing",
      category: "Science",
      isFeatured: true,
      tags: ["Quantum", "Technology", "Breakthrough"],
      author: "John Doe",
    },
    {
      id: 2,
      title: "Sports Team Wins Championship",
      content: "The local university's sports team has won the national championship for the third year in a row, thanks to a last-minute goal.",
      image: "https://via.placeholder.com/400x200.png?text=Sports+Victory",
      category: "Sports",
      isFeatured: true,
      tags: ["Sports", "Victory", "Championship"],
      author: "Jane Smith",
    },
    {
      id: 3,
      title: "New Discovery in Space Exploration",
      content: "Astronomers have discovered a new exoplanet that could potentially support life, sparking excitement in the scientific community.",
      image: "https://via.placeholder.com/400x200.png?text=Space+Discovery",
      category: "Science",
      isFeatured: true,
      tags: ["Space", "Astronomy", "Discovery"],
      author: "Dr. Emily Johnson",
    },
    {
      id: 4,
      title: "AI Revolutionizing Education",
      content: "Artificial Intelligence is transforming education by offering personalized learning experiences for students of all ages.",
      image: "https://via.placeholder.com/400x200.png?text=AI+in+Education",
      category: "Technology",
      isFeatured: true,
      tags: ["AI", "Education", "Innovation"],
      author: "Alex Martinez",
    },
    {
      id: 5,
      title: "Tech Startup Raises $10M in Funding",
      content: "A student-led tech startup has raised $10 million in a seed round, aiming to disrupt the e-commerce industry.",
      image: "https://via.placeholder.com/400x200.png?text=Startup+Funding",
      category: "Technology",
      isFeatured: false,
      tags: ["Startups", "Funding", "E-commerce"],
      author: "Sarah Lee",
    },
    {
      id: 6,
      title: "Local Theater Group Launches New Play",
      content: "The university's theater group has announced a new play set to debut next month, featuring a unique blend of drama and comedy.",
      image: "https://via.placeholder.com/400x200.png?text=Theater+Play",
      category: "Entertainment",
      isFeatured: false,
      tags: ["Theater", "Play", "Entertainment"],
      author: "Michael Brown",
    },
    {
      id: 7,
      title: "Student Develops Eco-Friendly Packaging",
      content: "A student entrepreneur has created an eco-friendly alternative to plastic packaging, which could significantly reduce waste.",
      image: "https://via.placeholder.com/400x200.png?text=Eco-Friendly+Innovation",
      category: "Science",
      isFeatured: false,
      tags: ["Sustainability", "Innovation", "Eco-friendly"],
      author: "Emma Watson",
    },
    {
      id: 8,
      title: "University Launches Mental Health Initiative",
      content: "The university has launched a new mental health initiative to support students' well-being during exam season.",
      image: "https://via.placeholder.com/400x200.png?text=Mental+Health+Initiative",
      category: "Others",
      isFeatured: false,
      tags: ["Mental Health", "Initiative", "Support"],
      author: "Rachel Green",
    },
    {
      id: 9,
      title: "Music Festival Brings Campus to Life",
      content: "The annual university music festival has returned, featuring performances from local artists and student bands.",
      image: "https://via.placeholder.com/400x200.png?text=Music+Festival",
      category: "Entertainment",
      isFeatured: true,
      tags: ["Music", "Festival", "Entertainment"],
      author: "Ross Geller",
    },
    {
      id: 10,
      title: "Cybersecurity Awareness Campaign Launched",
      content: "A new campaign aims to educate students and staff on best practices for online safety and cybersecurity.",
      image: "https://via.placeholder.com/400x200.png?text=Cybersecurity+Awareness",
      category: "Technology",
      isFeatured: false,
      tags: ["Cybersecurity", "Awareness", "Education"],
      author: "Monica Geller",
    },
    {
      id: 11,
      title: "Student Athletes to Represent University at National Games",
      content: "The university's student-athletes will compete in the national games next month, hoping to bring home gold medals.",
      image: "https://via.placeholder.com/400x200.png?text=Student+Athletes",
      category: "Sports",
      isFeatured: false,
      tags: ["Athletes", "Sports", "Games"],
      author: "Chandler Bing",
    },
    {
      id: 12,
      title: "Biotechnology Lab Makes Significant Discovery",
      content: "Researchers in the university's biotechnology lab have made a breakthrough discovery that could impact healthcare.",
      image: "https://via.placeholder.com/400x200.png?text=Biotechnology+Discovery",
      category: "Science",
      isFeatured: false,
      tags: ["Biotech", "Research", "Healthcare"],
      author: "Joey Tribbiani",
    },
    {
      id: 13,
      title: "Coding Bootcamp Sees Record Enrollment",
      content: "The university's coding bootcamp has seen record enrollment this semester, reflecting the growing demand for tech skills.",
      image: "https://via.placeholder.com/400x200.png?text=Coding+Bootcamp",
      category: "Technology",
      isFeatured: false,
      tags: ["Coding", "Bootcamp", "Tech"],
      author: "Phoebe Buffay",
    },
    {
      id: 14,
      title: "University Art Show Highlights Student Talent",
      content: "The annual art show displays student artwork, including paintings, sculptures, and digital art from various departments.",
      image: "https://via.placeholder.com/400x200.png?text=Art+Show",
      category: "Entertainment",
      isFeatured: false,
      tags: ["Art", "Exhibition", "Talent"],
      author: "Leonard Hofstadter",
    },
    {
      id: 15,
      title: "New Online Learning Platform Launched",
      content: "The university has launched a new online learning platform, allowing students to access courses and lectures remotely.",
      image: "https://via.placeholder.com/400x200.png?text=Online+Learning",
      category: "Technology",
      isFeatured: false,
      tags: ["Online Learning", "Platform", "Education"],
      author: "Sheldon Cooper",
    },
  ];
  
  export default demoArticles;
  